[gcp_service_account]
type = "service_account"
project_id = "chatbot-proyecto-479704"
private_key_id = "f10e56caa69556579cc5e37d4956b1e1a079bce8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAmJr0NHZWsRAF
+H6Emep/wUIV/l9YznFQoYBNXb7Vdjqac/5Oh+FfMq1OL56UC0NInPlWx9gxUMri\nFQtbpk0m9SWKvN06pcsyyR46OEB2olTn2EzDVHsSYVvU/EzIUwqdFAyFdYxwHePg
FaZrzejlE2eZK67U63niUj0sSij/Yi8et60/NRupPUaPDjQ1+x9kMdh5ucxV7JGG\nZLXV1gWrpxwW9go4K+aPpT25JxTn9CQT2Tp41Rog/eFyOH00VTori0QS3ZeLLdwy
bTnGisCEbv9Iq1lgcRrzQlP93k48xktxOgcHzq/w08I96Os4BdbTegvLdvs3GYny\nYFCQa0bpAgMBAAECggEAGIzbY7m0RAS6CCjO59Q+4h4ecHNGcCmQpDiSBEqo4sj5
W2rhxdzoS5xIHylOy4xL/VuVJQzAcDjeQ8du9TXTq92f9XlxseIkbsrYQY+eGAFF\nVXBrCJMiRQuICzRGDVsYhUFi/zgmuLv2qj/YQPG0eE7q68l3tch2dvUIuzaQ10zR
quKWPfKZLsJs/PSK6ikTarKWcv8jM+KxP0OptG3eHIbVWS3jZ6amlrRabOKF9y+a\nwXVPbwMNyeqb8W3dTXPD/eSXFotmtodQFKJu5dIlK32lPCPGaehzITAOiFbYtlhi
u6JXGypDzlkpE/dUGssVu4ASnFOnrx1wyeT5wMBCoQKBgQD7sXXISQy5dNlANDFF\nbDSZ45wlld8pQqMa3xInhBdKVZCWvAlGh4DL2HPHXEElYXamNGhQFScU3r+GFk18
slLPZd8xHfmRWy4IwnT612AwUIqECtnRoBaiCLlBKq6WPwnRkuTlYK/7akmDkM9F\nE5SFYvD09kxdaackIfKOYm80JQKBgQDD5EVaby0BwctNh368scA4xtIX93qXtKlY
Md3lKV6N6OezYdAAn9+un5GG/srCTcAswZd/7BeIsRn0wwKjANfHFRVl5+H2j6tK\nhYb/+9In1yOGR6enUwzpRKdbvtuZbubLA2D/pzNUWItdl5NdY8cqoFibYurgZiRh
i11IaKMKdQKBgBftGLs/ZnxCxVw7Gev1i1KNtoxEIQC1Gvg0+G7VObmRRLtviJox\ny2aVXvw2ouLAzxyhosDqIdr0CdTfTeJquUCJ+Jucs9rDhi7C/YfS7YvqPCCtP2OU
ClLA7YtqWUpjF7XadvPvKwuFYROmsm1onRfI/grrVvsSThc7OumaJeQZAoGAcPC2\nT6qTn1S1O1DocDBnbBStYqYLp1XA4Rl3Hr2YR2dF1zWIsCN82ngjdlqGWjprlyJS
j6118Bhzp5ubdJFy1tRADw3/SKGSl5eeuw3cH545XB0J+z21zvQHLa0/fRnktJ2R\nGjSzMmkOiPpwO0LgvKHQFF6WnqQlS5wHP00c21UCgYEA7eJC5CBNQ3JeGcr6U2vJ
XUeCq8nupgWjsDVZmZ2u1kut9yu9SY7C0kaj4H2drfAjbzpGShtYUs3g72YlPP4+\n0MejfSea7pi7ATT/n505VF5GbXhpTRzB0jwgfKTdTHUd3QfUaFfC8cx2xKuHN51t
TZmD2dIplqBm9I+k+95eGSY=
-----END PRIVATE KEY-----"""
client_email = "json-846@chatbot-proyecto-479704.iam.gserviceaccount.com"
client_id = "112816291421528219110"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/json-846%40chatbot-proyecto-479704.iam.gserviceaccount.com"
